CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS responses (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  email TEXT UNIQUE NOT NULL,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  response TEXT DEFAULT 'No response' CHECK (response IN ('Coming', 'Not coming', 'No response')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_responses_email ON responses(email);
CREATE INDEX IF NOT EXISTS idx_responses_updated_at ON responses(updated_at DESC);

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL
);

INSERT INTO admins (email, password_hash) VALUES
  ('mail@example.com', 'password_hash_here')
ON CONFLICT (email) DO NOTHING;